package com.bridgelabz;

import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class EmployeePayroll {

    /*
     * readEmployeePayrollData method to read database data sequentially and returning the
     * ArrayList of employees.
     */
    public List<EmployeePayrollData> readEmployeePayrollData() {
        String jdbcUrl = "jdbc:mysql://localhost:3306/payroll_service_new?characterEncoding=utf8";
        String username = "root";
        String password = "root123";

        /*
         * Taking an arraylist of type EmployeePayrollData and adding elements to the list one by one using
         * constructor of EmployeePayrollData class.
         */
        List<EmployeePayrollData> employeePayrollDataList = new ArrayList<>();
        try {
            System.out.println("Connecting to database " + jdbcUrl);
            /*
             * Making connection to the database by giving url,username and password of the database.
             */
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password);
            /*
             * If you want to execute a Statement object many times, it usually reduces execution time to use a
             * PreparedStatement object instead.
             */
            PreparedStatement preparedStatement = connection.prepareStatement("select * from employee_payroll ");
            /*
             * A ResultSet object is a table of data representing a database result set, which is usually generated by executing
             * a statement that queries the database.The object of ResultSet maintains a cursor pointing to a row of a table
             */
            ResultSet resultSet = preparedStatement.executeQuery();

            /*
             * Adding name,basic_pay and date of the employee in arraylist while resultSet.next() has elements inside
             */
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String name = resultSet.getString("name");
                double basic_pay = resultSet.getDouble("basic_pay");
                /*
                 * LocalDate is an immutable date-time object that represents a date, often viewed as year-month-day.
                 */
                LocalDate start = resultSet.getDate("start").toLocalDate();
                employeePayrollDataList.add(new EmployeePayrollData(id, name, basic_pay, start));
            }
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return employeePayrollDataList;
    }

    public List<EmployeePayrollData> updateBasic_pay(String name, double basic_pay) throws EmployeePayrollCustomException {

        String jdbcUrl = "jdbc:mysql://localhost:3306/payroll_service_new?characterEncoding=utf8";
        String username = "root";
        String password = "root123";
        List<EmployeePayrollData> employeePayrollDataList = new ArrayList<>();
        try {
            System.out.println("Connecting to database " + jdbcUrl);
            /*
             * Making connection to the database by giving url,username and password of the database.
             */
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password);


            String query = "update employee_payroll set basic_pay= ? where name= ?";
            /*
             * If you want to execute a Statement object many times, it usually reduces execution time to use a
             * PreparedStatement object instead.
             */
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            /*
             * First element is the parameterIndex in preparedStatement.setInt and second element is what we have to set
             * at first question mark there is set basic_pay and Second question mark states where there is name teresa.
             */
            preparedStatement.setDouble(1, basic_pay);
            preparedStatement.setString(2, "name");
            preparedStatement.executeUpdate();

            /*
             * Reading file after updating  the data in the database using resultSet  object
             */
            String sql = "select * from employee_payroll";
            /*
             * A ResultSet object is a table of data representing a database result set, which is usually generated by executing
             * a statement that queries the database.The object of ResultSet maintains a cursor pointing to a row of a table
             */
            ResultSet resultSet = preparedStatement.executeQuery(sql);

            /*
             * Adding name,basic_pay and date of the employee in arraylist while resultSet.next() has elements inside
             */
            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                name = resultSet.getString("name");
                basic_pay = resultSet.getDouble("basic_pay");
                /*
                 * LocalDate is an immutable date-time object that represents a date, often viewed as year-month-day.
                 */
                LocalDate start = resultSet.getDate("start").toLocalDate();
                employeePayrollDataList.add(new EmployeePayrollData(id, name, basic_pay, start));
            }
            connection.close();
        } catch (Exception e) {
            /*
             * Throwing the custom exception if got error while updating salary
             */
            throw new EmployeePayrollCustomException("Error while updating the salary");
        }
        return employeePayrollDataList;
    }
}